apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          command: [ "/bin/sh", "-c" ]
          args: [ "sleep 40 && nginx -g 'daemon off;'" ]  # Simulates a slow startup
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10   # Delay before the first check
            periodSeconds: 5           # Check readiness every 5 seconds